### ISSUE TITLE
Minor Errors & comments

### ISSUE THREAD

**Issue by gbouras13** [beardymcjohnface/Snaketool#3]
Hi Mike,

I'm playing around with this. It is amazingly simple and easy to use.

2 small things:

1. I think it would be best to include in the readme a bit more information about installing cookiecutter e.g.
 
```
conda create -n cookiecutterENV cookiecutter 
conda activate cookiecutterENV
cookiecutter https://github.com/beardymcjohnface/Snaketool.git
```

2. Error in the setup.py 

```
 │ exit code: 1
  ╰─> [1 lines of output]
      error in setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '3.9'
```

This was fixed when I changed the line in setup.py to:

python_requires=">=3.9"

instead of 

python_requires="3.9"

which is what I got by default.

George

**Comment by beardymcjohnface** [comment]
Thanks George! I had run into this myself, fixed it, forgot about it, misread your post and added the bug back in :p
Let me know if you spot anything else, or if you're not busy you could create a pull request with any fixes etc and get your face on the page as a contributor.
