### ISSUE TITLE
pip install "Could not find a version that satisfies the requirement snakemake7.22"

### ISSUE THREAD

**Issue by MelinaKlostermann** [beardymcjohnface/Snaketool#6]
Hi,
thanks a lot for building this really nice template. I was looking for something like this as I finished building a snakemake pipeline but have no experience in building command line tools. I started folowing the "Customising your Snaketool" guide, but alredy get a problem with the pip install:

> pip install -e .
Obtaining file:///media/storage/home/mklostermann/racoon
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of racoon to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement snakemake7.22 (from racoon) (from versions: none)
ERROR: No matching distribution found for snakemake7.22

As I understood it the  install_requires tools will be installed with pip. However, snakemake seems to only do conda/mamba installation? Should I install snakemake myself with conda (I am in an empty environment) before the pip install command?

**Comment by MelinaKlostermann** [comment]
Solved :) I changed 

install_requires=[
        "snakemake7.22",
to 
install_requires=[
        "snakemake>=7.22",

the setup.py file. I guess that typo comes from the cookiecuter setup?

**Comment by beardymcjohnface** [comment]
It might not be immediately clear but the `>=` is part of the cookiecutter field. The idea being that you can specify either a minimum version or a specific version. I'll see if I can add a help message to these fields.
